# 网站设置
title: ccjm 的博客
SEOTitle: ccjm的博客 | BY Blog
header-img: img/post-bg-desk.jpg
email: ccjm68371@gmail.com
description: "记录学习与成长的点滴"
keyword: "ccjm, ccjm的博客, 技术博客, 开发, 网络安全, web安全, 渗透测试, 漏洞挖掘"
url: "http://ccjmcc.github.io"          # 你的主机地址，用于绝对URL
baseurl: ""      # 例如，如果博客托管在 'host/blog' 上，填写 '/blog'
github_repo: "https://github.com/ccjmcc/ccjmcc.github.io.git" # 你的代码仓库（改成你的仓库地址）

# 侧边栏设置
sidebar: true                           # 是否使用侧边栏
sidebar-about-description: "坚持记录，持续成长"
sidebar-avatar: /img/about-BY-gentle.jpg      # 使用绝对URL，因为在 '/' 和 '/about/' 都会使用



# 社交媒体设置
RSS: false
# weibo_username:     
zhihu_username:     
github_username:    
facebook_username:  
jianshu_username:   
#twitter_username:   




# 构建设置
# 自2016年起，GitHub Pages不再支持 'pygments'。请使用 'rouge' 进行语法高亮。
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # 如果想要自定义锚点，请查看 `post.html` 的第181行



# Gems
# 来自PR#40，用于支持 Jekyll 3.0 的本地预览
gems: [jekyll-paginate]




# Markdown 设置
# 将 redcarpet 替换为 kramdown
# 虽然 redcarpet 可以自动高亮代码，但缺少 header-id 使得目录功能无法实现，所以我切换到 kramdown
# 文档: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # 使用 Github Flavored Markdown !重要



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论（设置为false关闭评论）
  clientID: f2c84e7629bb1446c1a4                            #生成的clientID
  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret
  repo: ccjmcc.github.io    #仓库名称
  owner: ccjmcc    #github用户名
  admin: ccjmcc
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# 分析设置
# 百度统计
ba_track_id: 645c513fce9bea43b399f9eea61271a1

# Google Analytics（可选，如果不需要可以留空）
ga_track_id: 'G-TNGCS7Q58L'            # 格式: UA-xxxxxx-xx (旧版) 或 G-XXXXXXXX (GA4新版)
ga_domain: 'auto'          # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# 特色标签
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# 渐进式网页应用
chrome-tab-theme-color: "#000000"
service-worker: true



# 友情链接
friends: [
    {
        title: "WY",
        href: ""
    },{
        title: "简书·BY",
        href: ""
    },{
        title: "Apple",
        href: ""
    },{
        title: "Apple Developer",
        href: ""
    }
]
